apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codgen-0606-new 
  janus-idp.io/tekton: codgen-0606-new
  backstage.io/kubernetes-id: codgen-0606-new
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: codgen-0606-new
resources: 
- application-dev.yaml