apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: codgen-0606-new-gitops
  description: This is GitOps manifest for codgen-0606-new   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: codgen-0606-new
    janus-idp.io/tekton: codgen-0606-new 
    backstage.io/kubernetes-id: codgen-0606-new 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:codgen-0606-new
