apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codgen-0606-new
  janus-idp.io/tekton: codgen-0606-new
  backstage.io/kubernetes-id: codgen-0606-new
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: codgen-0606-new
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment.yaml
- route.yaml
- service.yaml
