---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models-cache-codgen-0606-new
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi